# Generated by Django 5.0.3 on 2024-03-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Person',
        ),
    ]
