# Generated by Django 5.0.3 on 2024-03-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_rename_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='address2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='state_province',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
